// ─── Gemeinsame Event Library ────────────────────────────────────────────────

export const _IMGS = [
  "/event-back2dock.jpg", "/event-jerome.jpg", "/event-sixteenbeats.jpg",
  "/event-strictlyoldschool.jpg", "/event-kuult.jpg", "/doc50-concert-1.jpg",
  "/doc50-concert-2.jpg", "/doc50-concert-3.jpg", "/doc50-concert-5.jpg", "/doc50-concert-6.jpg",
];

function deriveHasTicket(ev) {
  ev.hasTicket = !!ev.ticketUrl;
  return ev;
}

export const eventLibrary = [
  { id: "",  titel: "Back2Dock",          untertitel: "", beschreibung: "Die traditionelle Back2Dock Nacht kehrt zurück in die DOCK50 Skylounge.",                              datum: "14.03.26", einlass: "", beginn: "", veranstaltort: "", raum: "Skylounge", veranstalter: "", rubrik: "", preis: null, status: [], externeUrl: "", ticketUrl: "/anfrage.html", zusatzoption: "", bildGross: _IMGS[0], bildKlein: "" },
  { id: "",  titel: "Jerome",             untertitel: "", beschreibung: "Jerome bringt seinen unverwechselbaren Sound live auf die Skylounge-Bühne.",                            datum: "28.03.26", einlass: "", beginn: "", veranstaltort: "", raum: "Skylounge", veranstalter: "", rubrik: "", preis: null, status: [], externeUrl: "", ticketUrl: "/anfrage.html", zusatzoption: "", bildGross: _IMGS[1], bildKlein: "" },
  { id: "",  titel: "Sixteen Beats",      untertitel: "", beschreibung: "Das DJ Collective bringt sechzehn Beats, die die Nacht zum Leben erwecken.",                            datum: "11.04.26", einlass: "", beginn: "", veranstaltort: "", raum: "Skylounge", veranstalter: "", rubrik: "", preis: null, status: [], externeUrl: "", ticketUrl: "/anfrage.html", zusatzoption: "", bildGross: _IMGS[2], bildKlein: "" },
  { id: "",  titel: "Strictly Oldschool", untertitel: "", beschreibung: "Eine Nacht ganz im Zeichen der klassischen Sounds – Strictly Oldschool.",                               datum: "18.04.26", einlass: "", beginn: "", veranstaltort: "", raum: "Skylounge", veranstalter: "", rubrik: "", preis: null, status: [], externeUrl: "", ticketUrl: "/anfrage.html", zusatzoption: "", bildGross: _IMGS[3], bildKlein: "" },
  { id: "",  titel: "Kuult",              untertitel: "", beschreibung: "Kuult live – emotionale Songs und kraftvolle Bühnenperformance.",                                       datum: "09.05.26", einlass: "", beginn: "", veranstaltort: "", raum: "Skylounge", veranstalter: "", rubrik: "", preis: null, status: [], externeUrl: "", ticketUrl: "/anfrage.html", zusatzoption: "", bildGross: _IMGS[4], bildKlein: "" },
  { id: "",  titel: "{Infos}",            untertitel: "", beschreibung: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.", datum: "23.05.26", einlass: "", beginn: "", veranstaltort: "", raum: "Skylounge", veranstalter: "", rubrik: "", preis: null, status: [], externeUrl: "", ticketUrl: "/anfrage.html", zusatzoption: "", bildGross: _IMGS[5], bildKlein: "" },
  { id: "",  titel: "{Infos}",            untertitel: "", beschreibung: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.", datum: "06.06.26", einlass: "", beginn: "", veranstaltort: "", raum: "Skylounge", veranstalter: "", rubrik: "", preis: null, status: [], externeUrl: "", ticketUrl: "",               zusatzoption: "", bildGross: _IMGS[6], bildKlein: "" },
  { id: "",  titel: "{Infos}",            untertitel: "", beschreibung: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.", datum: "20.06.26", einlass: "", beginn: "", veranstaltort: "", raum: "Skylounge", veranstalter: "", rubrik: "", preis: null, status: [], externeUrl: "", ticketUrl: "/anfrage.html", zusatzoption: "", bildGross: _IMGS[7], bildKlein: "" },
  { id: "",  titel: "{Infos}",            untertitel: "", beschreibung: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.", datum: "04.07.26", einlass: "", beginn: "", veranstaltort: "", raum: "Skylounge", veranstalter: "", rubrik: "", preis: null, status: [], externeUrl: "", ticketUrl: "",               zusatzoption: "", bildGross: _IMGS[8], bildKlein: "" },
  { id: "", titel: "{Infos}",            untertitel: "", beschreibung: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.", datum: "18.07.26", einlass: "", beginn: "", veranstaltort: "", raum: "Skylounge", veranstalter: "", rubrik: "", preis: null, status: [], externeUrl: "", ticketUrl: "",               zusatzoption: "", bildGross: _IMGS[9], bildKlein: "" },
  { id: "", titel: "{Infos}",            untertitel: "", beschreibung: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.", datum: "01.08.26", einlass: "", beginn: "", veranstaltort: "", raum: "Skylounge", veranstalter: "", rubrik: "", preis: null, status: [], externeUrl: "", ticketUrl: "/anfrage.html", zusatzoption: "", bildGross: _IMGS[0], bildKlein: "" },
  { id: "", titel: "{Infos}",            untertitel: "", beschreibung: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.", datum: "15.08.26", einlass: "", beginn: "", veranstaltort: "", raum: "Skylounge", veranstalter: "", rubrik: "", preis: null, status: [], externeUrl: "", ticketUrl: "",               zusatzoption: "", bildGross: _IMGS[1], bildKlein: "" },
  { id: "", titel: "{Infos}",            untertitel: "", beschreibung: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.", datum: "12.09.26", einlass: "", beginn: "", veranstaltort: "", raum: "Skylounge", veranstalter: "", rubrik: "", preis: null, status: [], externeUrl: "", ticketUrl: "",               zusatzoption: "", bildGross: _IMGS[2], bildKlein: "" },
  { id: "", titel: "{Infos}",            untertitel: "", beschreibung: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.", datum: "03.10.26", einlass: "", beginn: "", veranstaltort: "", raum: "Skylounge", veranstalter: "", rubrik: "", preis: null, status: [], externeUrl: "", ticketUrl: "/anfrage.html", zusatzoption: "", bildGross: _IMGS[3], bildKlein: "" },
  { id: "", titel: "{Infos}",            untertitel: "", beschreibung: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.", datum: "14.11.26", einlass: "", beginn: "", veranstaltort: "", raum: "Skylounge", veranstalter: "", rubrik: "", preis: null, status: [], externeUrl: "", ticketUrl: "",               zusatzoption: "", bildGross: _IMGS[4], bildKlein: "" },
  { id: "", titel: "{Infos}",            untertitel: "", beschreibung: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.", datum: "31.12.26", einlass: "", beginn: "", veranstaltort: "", raum: "Skylounge", veranstalter: "", rubrik: "", preis: null, status: [], externeUrl: "", ticketUrl: "",               zusatzoption: "", bildGross: _IMGS[5], bildKlein: "" },
  { id: "", titel: "{Infos}",            untertitel: "", beschreibung: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.", datum: "10.01.27", einlass: "", beginn: "", veranstaltort: "", raum: "Skylounge", veranstalter: "", rubrik: "", preis: null, status: [], externeUrl: "", ticketUrl: "/anfrage.html", zusatzoption: "", bildGross: _IMGS[6], bildKlein: "" },
  { id: "", titel: "{Infos}",            untertitel: "", beschreibung: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.", datum: "14.02.27", einlass: "", beginn: "", veranstaltort: "", raum: "Skylounge", veranstalter: "", rubrik: "", preis: null, status: [], externeUrl: "", ticketUrl: "",               zusatzoption: "", bildGross: _IMGS[7], bildKlein: "" },
  { id: "", titel: "{Infos}",            untertitel: "", beschreibung: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.", datum: "20.03.27", einlass: "", beginn: "", veranstaltort: "", raum: "Skylounge", veranstalter: "", rubrik: "", preis: null, status: [], externeUrl: "", ticketUrl: "",               zusatzoption: "", bildGross: _IMGS[8], bildKlein: "" },
  { id: "", titel: "{Infos}",            untertitel: "", beschreibung: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.", datum: "03.04.27", einlass: "", beginn: "", veranstaltort: "", raum: "Skylounge", veranstalter: "", rubrik: "", preis: null, status: [], externeUrl: "", ticketUrl: "/anfrage.html", zusatzoption: "", bildGross: _IMGS[9], bildKlein: "" },
  { id: "", titel: "{Infos}",            untertitel: "", beschreibung: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.", datum: "07.03.26", einlass: "", beginn: "", veranstaltort: "", raum: "Deck1", veranstalter: "", rubrik: "", preis: null, status: [], externeUrl: "", ticketUrl: "/anfrage.html", zusatzoption: "", bildGross: _IMGS[5], bildKlein: "" },
  { id: "", titel: "{Infos}",            untertitel: "", beschreibung: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.", datum: "21.03.26", einlass: "", beginn: "", veranstaltort: "", raum: "Deck1", veranstalter: "", rubrik: "", preis: null, status: [], externeUrl: "", ticketUrl: "/anfrage.html", zusatzoption: "", bildGross: _IMGS[6], bildKlein: "" },
  { id: "", titel: "{Infos}",            untertitel: "", beschreibung: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.", datum: "04.04.26", einlass: "", beginn: "", veranstaltort: "", raum: "Deck1", veranstalter: "", rubrik: "", preis: null, status: [], externeUrl: "", ticketUrl: "/anfrage.html", zusatzoption: "", bildGross: _IMGS[7], bildKlein: "" },
  { id: "", titel: "{Infos}",            untertitel: "", beschreibung: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.", datum: "19.04.26", einlass: "", beginn: "", veranstaltort: "", raum: "Deck1", veranstalter: "", rubrik: "", preis: null, status: [], externeUrl: "", ticketUrl: "/anfrage.html", zusatzoption: "", bildGross: _IMGS[8], bildKlein: "" },
  { id: "", titel: "{Infos}",            untertitel: "", beschreibung: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.", datum: "02.05.26", einlass: "", beginn: "", veranstaltort: "", raum: "Deck1", veranstalter: "", rubrik: "", preis: null, status: [], externeUrl: "", ticketUrl: "",               zusatzoption: "", bildGross: _IMGS[9], bildKlein: "" },
  { id: "", titel: "{Infos}",            untertitel: "", beschreibung: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.", datum: "16.05.26", einlass: "", beginn: "", veranstaltort: "", raum: "Deck1", veranstalter: "", rubrik: "", preis: null, status: [], externeUrl: "", ticketUrl: "",               zusatzoption: "", bildGross: _IMGS[0], bildKlein: "" },
  { id: "", titel: "{Infos}",            untertitel: "", beschreibung: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.", datum: "30.05.26", einlass: "", beginn: "", veranstaltort: "", raum: "Deck1", veranstalter: "", rubrik: "", preis: null, status: [], externeUrl: "", ticketUrl: "/anfrage.html", zusatzoption: "", bildGross: _IMGS[1], bildKlein: "" },
  { id: "", titel: "{Infos}",            untertitel: "", beschreibung: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.", datum: "13.06.26", einlass: "", beginn: "", veranstaltort: "", raum: "Deck1", veranstalter: "", rubrik: "", preis: null, status: [], externeUrl: "", ticketUrl: "",               zusatzoption: "", bildGross: _IMGS[2], bildKlein: "" },
  { id: "", titel: "{Infos}",            untertitel: "", beschreibung: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.", datum: "27.06.26", einlass: "", beginn: "", veranstaltort: "", raum: "Deck1", veranstalter: "", rubrik: "", preis: null, status: [], externeUrl: "", ticketUrl: "/anfrage.html", zusatzoption: "", bildGross: _IMGS[3], bildKlein: "" },
  { id: "", titel: "{Infos}",            untertitel: "", beschreibung: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.", datum: "11.07.26", einlass: "", beginn: "", veranstaltort: "", raum: "Deck1", veranstalter: "", rubrik: "", preis: null, status: [], externeUrl: "", ticketUrl: "",               zusatzoption: "", bildGross: _IMGS[4], bildKlein: "" },
  { id: "", titel: "{Infos}",            untertitel: "", beschreibung: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.", datum: "25.07.26", einlass: "", beginn: "", veranstaltort: "", raum: "Deck1", veranstalter: "", rubrik: "", preis: null, status: [], externeUrl: "", ticketUrl: "",               zusatzoption: "", bildGross: _IMGS[5], bildKlein: "" },
  { id: "", titel: "{Infos}",            untertitel: "", beschreibung: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.", datum: "08.08.26", einlass: "", beginn: "", veranstaltort: "", raum: "Deck1", veranstalter: "", rubrik: "", preis: null, status: [], externeUrl: "", ticketUrl: "/anfrage.html", zusatzoption: "", bildGross: _IMGS[6], bildKlein: "" },
  { id: "", titel: "{Infos}",            untertitel: "", beschreibung: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.", datum: "19.09.26", einlass: "", beginn: "", veranstaltort: "", raum: "Deck1", veranstalter: "", rubrik: "", preis: null, status: [], externeUrl: "", ticketUrl: "",               zusatzoption: "", bildGross: _IMGS[7], bildKlein: "" },
  { id: "", titel: "{Infos}",            untertitel: "", beschreibung: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.", datum: "10.10.26", einlass: "", beginn: "", veranstaltort: "", raum: "Deck1", veranstalter: "", rubrik: "", preis: null, status: [], externeUrl: "", ticketUrl: "",               zusatzoption: "", bildGross: _IMGS[8], bildKlein: "" },
  { id: "", titel: "{Infos}",            untertitel: "", beschreibung: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.", datum: "21.11.26", einlass: "", beginn: "", veranstaltort: "", raum: "Deck1", veranstalter: "", rubrik: "", preis: null, status: [], externeUrl: "", ticketUrl: "/anfrage.html", zusatzoption: "", bildGross: _IMGS[9], bildKlein: "" },
  { id: "", titel: "{Infos}",            untertitel: "", beschreibung: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.", datum: "31.12.26", einlass: "", beginn: "", veranstaltort: "", raum: "Deck1", veranstalter: "", rubrik: "", preis: null, status: [], externeUrl: "", ticketUrl: "",               zusatzoption: "", bildGross: _IMGS[0], bildKlein: "" },
  { id: "", titel: "{Infos}",            untertitel: "", beschreibung: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.", datum: "17.01.27", einlass: "", beginn: "", veranstaltort: "", raum: "Deck1", veranstalter: "", rubrik: "", preis: null, status: [], externeUrl: "", ticketUrl: "",               zusatzoption: "", bildGross: _IMGS[1], bildKlein: "" },
  { id: "", titel: "{Infos}",            untertitel: "", beschreibung: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.", datum: "21.02.27", einlass: "", beginn: "", veranstaltort: "", raum: "Deck1", veranstalter: "", rubrik: "", preis: null, status: [], externeUrl: "", ticketUrl: "/anfrage.html", zusatzoption: "", bildGross: _IMGS[2], bildKlein: "" },
  { id: "", titel: "{Infos}",            untertitel: "", beschreibung: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.", datum: "27.03.27", einlass: "", beginn: "", veranstaltort: "", raum: "Deck1", veranstalter: "", rubrik: "", preis: null, status: [], externeUrl: "", ticketUrl: "",               zusatzoption: "", bildGross: _IMGS[3], bildKlein: "" },
  { id: "", titel: "{Infos}",            untertitel: "", beschreibung: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.", datum: "10.04.27", einlass: "", beginn: "", veranstaltort: "", raum: "Deck1", veranstalter: "", rubrik: "", preis: null, status: [], externeUrl: "", ticketUrl: "",               zusatzoption: "", bildGross: _IMGS[4], bildKlein: "" },
].map(deriveHasTicket);

export function parseEventDate(str) {
  const [d, m, y] = str.split(".").map(Number);
  return new Date(2000 + y, m - 1, d);
}

export function getNearestN(filter, n = 8) {
  const today = new Date();
  today.setHours(0, 0, 0, 0);
  const pool = filter === "all"
    ? eventLibrary
    : eventLibrary.filter(ev => ev.raum.toLowerCase() === filter.toLowerCase());
  return pool
    .filter(ev => parseEventDate(ev.datum) >= today)
    .sort((a, b) => parseEventDate(a.datum) - parseEventDate(b.datum))
    .slice(0, n);
}

export function findEvent(loc, date) {
  return eventLibrary.find(ev =>
    ev.raum.toLowerCase() === loc?.toLowerCase() && ev.datum === date
  ) || null;
}
